name = "aoc_2025"
version = "0.1.0"
description = "Advent of Code 2025 in Gleam"
target = "erlang"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp     = ">= 0.10.0 and < 2.0.0"
gleam_erlang  = ">= 1.0.0 and < 2.0.0"
simplifile    = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit      = ">= 1.0.0 and < 2.0.0"
